sudo: required

language: php

php:
  - '7.2'

env:
  global:
    - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - CODE_COVERAGE="--coverage-clover=coverage.clover"

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - if [[ -z $CODE_COVERAGE ]]; then phpenv config-rm xdebug.ini ; fi
  - composer self-update

install:
  - travis_retry composer update

script:
  - ./vendor/bin/phpunit $CODE_COVERAGE

after_script:
  - if [[ -n $CODE_COVERAGE ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ -n $CODE_COVERAGE ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
